[package]
name = "arceos-watchdog_test"
version = "0.1.0"
edition.workspace = true
authors = ["Chang Xu <xuxchang@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axstd = { workspace = true, optional = true }
